version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
      - /home/nerdless/de-course-412517-66c29960b993.json:/.google/credentials/google_credentials.json
    network_mode: host